#!/usr/bin/env python3
"""
Generate root .gitignore for crosside workspace.

Focus:
- binaries (.a, .so, .apk, .wasm, executables)
- generated build folders under projects/ and modules/
"""

from __future__ import annotations

import argparse
from pathlib import Path


GLOBAL_PATTERNS = [
    "# Auto-generated by tools/generate_gitignore.py",
    "",
    "# Python",
    "__pycache__/",
    "*.py[cod]",
    "",
    "# Editors/OS",
    "*.swp",
    ".DS_Store",
    "Thumbs.db",
    "",
    "# Logs/dumps",
    "*.log",
    "*.dump",
    "",
    "# Generic binaries/artifacts",
    "*.a",
    "*.o",
    "*.obj",
    "*.so",
    "*.dll",
    "*.dylib",
    "*.exe",
    "*.out",
    "*.class",
    "*.jar",
    "*.apk",
    "*.ap_",
    "*.dex",
    "*.wasm",
    "*.bc",
    "*.pdb",
    "*.dSYM/",
    "",
]


BUILD_DIRS = ("obj", "bin", "out", "tmp", "dex")
PLATFORM_DIRS = ("Android", "Web", "Linux", "Windows", "macOS")
ROOTS_TO_SCAN = ("projects", "modules")


def collect_generated_dirs(repo_root: Path) -> list[str]:
    lines: list[str] = []
    for top in ROOTS_TO_SCAN:
        base = repo_root / top
        if not base.is_dir():
            continue
        for name in BUILD_DIRS + PLATFORM_DIRS:
            lines.append(f"/{top}/*/{name}/")
    return lines


def build_gitignore_text(repo_root: Path) -> str:
    out = list(GLOBAL_PATTERNS)
    out.append("# Generated build directories")
    out.extend(collect_generated_dirs(repo_root))
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate root .gitignore")
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root path (default: current directory)",
    )
    parser.add_argument(
        "--output",
        default=".gitignore",
        help="Output .gitignore path (default: .gitignore at repo root)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print generated content and exit")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    output_path = (repo_root / args.output).resolve() if not Path(args.output).is_absolute() else Path(args.output)
    text = build_gitignore_text(repo_root)

    if args.dry_run:
        print(text)
        return 0

    output_path.write_text(text, encoding="utf-8")
    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
